SELECT
    e.FIRST_NAME, 
    e.MIDDLE_NAME, 
    e.LAST_NAME, 
    e.STUDENT_NUMBER, 
    e.STATE_STUDENTNUMBER, 
    e.GRADE_LEVEL,
    e.SCHOOLID,
    sch.NAME AS SCHOOL_NAME,
    e.HOME_ROOM AS TEACHER,
    e.PL_LANGUAGE,
    e.DOB,
    e.GENDER,
    r.RACECD,
    e.ETHNICITY,
    e.FEDETHNICITY,
    e.STREET,
    e.CITY,
    e.STATE,
    e.ZIP,
    e.HOME_PHONE

FROM 
    STUDENTS e
    LEFT JOIN STUDENTRACE r ON r.STUDENTID = e.ID
    LEFT JOIN SCHOOLS sch ON e.SCHOOLID = sch.SCHOOL_NUMBER
    
WHERE
    e.GRADE_LEVEL BETWEEN -1 AND 0
    AND e.SCHOOLID NOT IN ('777777','888888')
    AND e.EXITCODE IS NULL
    

ORDER BY e.LAST_NAME ASC
