-- Physical Fitness Test Results for each site

WITH testtype AS (
    SELECT 
        t.TESTSCOREID,
        MIN(ts.NAME) as NAME
    FROM STUDENTTESTSCORE t
    JOIN TESTSCORE ts
        ON ts.ID = t.TESTSCOREID
    GROUP BY t.TESTSCOREID
),

testdate AS (
    SELECT
        t.STUDENTID,
        st.GRADE_LEVEL,
        MIN(st.TEST_DATE) AS TESTDATE
    FROM STUDENTTESTSCORE t
    JOIN STUDENTTEST st
        ON st.ID = t.STUDENTTESTID
    GROUP BY t.STUDENTID, st.GRADE_LEVEL
)

SELECT 
    t.DCID,
    t.STUDENTID,
    s.STUDENT_NUMBER,
    d.GRADE_LEVEL,
    s.SCHOOLID,
    tt.NAME AS TEST_TYPE,
    d.TESTDATE,
    t.STUDENTTESTID,
    t.NUMSCORE,
    t.PERCENTSCORE,
    t.ALPHASCORE,
    t.NOTES  
    
FROM STUDENTTESTSCORE t
LEFT JOIN STUDENTS s
    ON s.id = t.studentid
LEFT JOIN TESTTYPE tt
    ON tt.TESTSCOREID = t.TESTSCOREID
LEFT JOIN TESTDATE d
    ON d.STUDENTID = t.STUDENTID
    
WHERE t.TESTSCOREID IN (1,2,3,4,5,6,7,8,9,10,11)
    AND s.ENROLL_STATUS = 0
    AND d.TESTDATE BETWEEN TO_DATE('10-AUG-2024', 'DD-MON-YYYY')
                   AND TO_DATE('06-JUN-2025', 'DD-MON-YYYY')
    
ORDER BY s.SCHOOLID, s.GRADE_LEVEL, tt.NAME
